---

# Same timestamp for all variables
_playbook_timestamp: "{{ timestamp_override | default(ansible_date_time.epoch) }}"

# These variables can/should be overridden by the user of the role.
aws_asg_input:
  app_name: goodtimes
  app_version: 1x0 # TODO: Must not contain dots. Handle it!

# These variables should/must be overridden by the user of the role
vpc: ""
region: "eu-west-1"
subnets: []
aws_key: ""
instance_type: t2.small
image_id: ami-07c3a868617f8acdb  # TODO: Find the newest AWS Linux 2 AMI dynamically
instance_profile: ""
route53_zone: bettercode.se
docker_image: nginx

# ?
user_data_content: "{{ lookup('template', 'userdata.sh') }}"

# These variables should not need to be (but can be) overridden by the user of the role.
# A unique ASG name ensures that the ASG will always be created, never updated.
# (Hence the combination of variables, including timestamp.)
_aws_stack:
  name: "stack-{{ aws_asg_input.app_name }}-{{ aws_asg_input.app_version }}-{{ _playbook_timestamp }}"

_aws_asg:
  name: "asg-{{ aws_asg_input.app_name }}-{{ aws_asg_input.app_version }}-{{ _playbook_timestamp }}"

_aws_tg:
  name: "tg-{{ aws_asg_input.app_name }}-{{ aws_asg_input.app_version }}-{{ _playbook_timestamp }}"

_aws_instance_sg:
  name: "sec-for-instances-{{ aws_asg_input.app_name }}-{{ aws_asg_input.app_version }}-{{ _playbook_timestamp }}"

_aws_lc_basename: "lc-{{ aws_asg_input.app_name }}"

_aws_lc:
  name: "{{ _aws_lc_basename }}-{{ aws_asg_input.app_version }}-{{ _playbook_timestamp }}"

_aws_sg_for_lb:
  name: "sec-for-lb-{{ aws_asg_input.app_name }}-{{ aws_asg_input.app_version }}-{{ _playbook_timestamp }}"

_aws_lb:
  name: "lb-{{ aws_asg_input.app_name }}-{{ aws_asg_input.app_version }}-{{ _playbook_timestamp }}"

_aws_tags_dict:
  app_name: "{{ aws_asg_input.app_name }}"
  app_version: "{{ aws_asg_input.app_version }}"

_aws_tags:
  - app_name: "{{ aws_asg_input.app_name }}"
  - app_version: "{{ aws_asg_input.app_version }}"

_aws_tags_for_cleanup:
  app_name: "{{ aws_asg_input.app_name }}"
