---

- name: "Find all stacks"
  cloudformation_facts:
    region: "{{ region }}"
  register: _all_stacks
  tags: [cleanup]

- name: "Delete old stacks"  # Parsing the result from the cloudformation module is not simple.
  cloudformation:
    stack_name: "{{ item.key }}"
    state: absent
    region: "{{ region }}"
  when: item.key != _aws_stack.name
  loop: "{{ lookup('dict', _all_stacks.ansible_facts.cloudformation, wantlist=True) }}"
  loop_control:
    label: "{{ item.key }}"
  tags: [cleanup]
