---

- hosts: localhost
  connection: local
  gather_facts: yes  # needed for ansible_date_time
  roles:
    - role: betrcode.aws-ecr
    - role: betrcode.aws-cf-asg
      docker_image: "{{ _tag }}" # Coming from previous role
